### ISSUE TITLE
Member List Misaligned

### ISSUE THREAD

**Issue by polyjitter** [asportnoy/compact-discord#1]
It appears the members list is offset incorrectly, as follows:

![image](https://github.com/asportnoy/compact-discord/assets/18127936/5509125c-c95a-40e0-b9b0-4b2db7585c8f)
![image](https://github.com/asportnoy/compact-discord/assets/18127936/541233a5-b76c-47ec-91b0-7ff468775b63)

**Comment by HelmicNewciv** [comment]
Can confirm.  Exported it as a CSS to use in Vencord.  It does fine at about 500-ish px wide on my tiling desktop, but when I halve that width again the member list does exactly what's in that gif.

Great CSS though, extremely useful for tiling desktops.

**Comment by polyjitter** [comment]
This, or a similar issue, still appears in the newest version:
![image](https://github.com/asportnoy/compact-discord/assets/18127936/6aa7d4a5-3a84-45d1-8784-bb83ef1414ca)

**Comment by HelmicNewciv** [comment]
> This, or a similar issue, still appears in the newest version

The PR I submitted (#2) fixes this, it's just changing out one variable to make sure it's grabbing the entire container.
